kind: Deployment
apiVersion: apps/v1
metadata:
  name: centos
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: centos
      app.kubernetes.io/instance: centos
      app.kubernetes.io/name: centos
  template:
    metadata:
      labels:
        app: centos
        app.kubernetes.io/component: centos
        app.kubernetes.io/instance: centos
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: centos
    spec:
      containers:
      - name: centos
        image: centos
        resources:
          requests:
            cpu: 25m
            memory: 500Mi
          limits:
            cpu: 30m
            memory: 1024Mi
