apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-monitor-grafana-data
  labels:
    type: local
    volume: app-monitor-volume
spec:
  storageClassName: local
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/augustu/Mount/Develop/data/kubernetes/app-monitor-grafana-data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-data
  namespace: app-monitor
  finalizers:
    - kubernetes.io/pvc-protection
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2021-04-24T08:57:12Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/name': {}
        'f:spec':
          'f:accessModes': {}
          'f:resources':
            'f:requests':
              .: {}
              'f:storage': {}
          'f:selector': {}
          'f:volumeMode': {}
        'f:status':
          'f:phase': {}
  selfLink: >-
    /api/v1/namespaces/app-monitor/persistentvolumeclaims/grafana-data
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      volume: app-monitor-volume
  resources:
    requests:
      storage: 5Gi
  storageClassName: local
  volumeMode: Filesystem
status:
  phase: Pending
